apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-api-service
spec:
  type: NodePort
  selector:
    app: spring-boot-demo
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30888

